ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.adel.plugins.HttpKt.configureHttp
      - com.adel.plugins.SerializationKt.configureSerialization
      - com.adel.plugins.StatusPagesKt.configureStatusPages
      - com.adel.plugins.RoutingKt.configureRouting
