package com.adel.common.data

import java.util.Properties

/**
 * Reads build metadata baked in at compile time.
 * The build-info.properties file is generated by a Gradle task
 * (see build.gradle.kts) from the project version.
 */
object BuildInfo {
    val version: String by lazy {
        runCatching {
            BuildInfo::class.java
                .getResourceAsStream("/build-info.properties")
                ?.use { stream ->
                    Properties().apply { load(stream) }.getProperty("version")
                }
        }.getOrNull() ?: "unknown"
    }
}