package com.adel.features.matches.domain

object TeamCodes {
    private val nameToCode = mapOf(
        "Algeria" to "dz",
        "Argentina" to "ar",
        "Australia" to "au",
        "Austria" to "at",
        "Belgium" to "be",
        "Bosnia and Herzegovina" to "ba",
        "Brazil" to "br",
        "Cabo Verde" to "cv",
        "Canada" to "ca",
        "Colombia" to "co",
        "Croatia" to "hr",
        "Curaçao" to "cw",
        "Czech Republic" to "cz",
        "DR Congo" to "cd",
        "Côte d’Ivoire" to "ci",
        "Ecuador" to "ec",
        "Egypt" to "eg",
        "England" to "en",
        "France" to "fr",
        "Germany" to "de",
        "Ghana" to "gh",
        "Haiti" to "ht",
        "Iran" to "ir",
        "Iraq" to "iq",
        "Japan" to "jp",
        "Jordan" to "jo",
        "Mexico" to "mx",
        "Morocco" to "ma",
        "Netherlands" to "nl",
        "New Zealand" to "nz",
        "Norway" to "no",
        "Panama" to "pa",
        "Paraguay" to "py",
        "Portugal" to "pt",
        "Qatar" to "qa",
        "Saudi Arabia" to "sa",
        "Scotland" to "sc",
        "Senegal" to "sn",
        "South Africa" to "za",
        "South Korea" to "kr",
        "Spain" to "es",
        "Sweden" to "se",
        "Switzerland" to "ch",
        "Tunisia" to "tn",
        "Türkiye" to "tr",
        "United States" to "us",
        "Uruguay" to "uy",
        "Uzbekistan" to "uz"
    )

    fun fromTeamName(name: String): String? = nameToCode[name]
}
